export const GET_ALL_BOOKS = "GET_ALL_BOOKS";
export const GET_ALL_BOOKS_RESOLVED = "GET_ALL_BOOKS_RESOLVED";
export const GET_ALL_BOOKS_FAILED = "GET_ALL_BOOKS_FAILED";

export const SELECT_BOOK = "SELECT_BOOK";
export const SELECT_BOOK_RESOLVED = "SELECT_BOOK_RESOLVED";
export const SELECT_BOOK_FAILED = "SELECT_BOOK_FAILED";


export const SELECT_DURATION_IN_DAYS = "SELECT_DURATION_IN_DAYS";
export const SELECT_DURATION_IN_DAYS_RESOLVED = "SELECT_DURATION_IN_DAYS_RESOLVED";
export const SELECT_DURATION_IN_DAYS_FAILED = "SELECT_DURATION_IN_DAYS_FAILED";